apiVersion: apps/v1
kind: Deployment
metadata:
  name: cozy-telemetry
  labels:
    app: cozy-telemetry
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cozy-telemetry
  template:
    metadata:
      labels:
        app: cozy-telemetry
    spec:
      containers:
      - name: cozy-telemetry
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--forward-url={{ .Values.config.forwardURL }}"
          - "--listen-addr={{ .Values.config.listenAddr }}"
          - "--vmselect-url={{ .Values.config.vmSelectURL }}"
          - "--snapshot-dir={{ .Values.config.snapshotDir }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: snapshots
          mountPath: /data/snapshots
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: snapshots
        persistentVolumeClaim:
          claimName: cozy-telemetry-snapshots
