apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cozy-telemetry-snapshots
  labels:
    app: cozy-telemetry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.snapshot.storage }}
