{
 "title": "Telemetry",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "COZYSTACK Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  max by (cluster_id) (cozy_nodes_count)\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "COZYSTACK version setup",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 10, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (cozystack_version) (\n  count by (cluster_id, cozystack_version) (cozy_cluster_info)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "COZYSTACK clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    sum by (__name__, cluster_id) (cozy_cluster_info),\n    \"__name__\", \n    \"total_cluster_sum\", \n    \"\", \n    \"\"\n  )\n)\n\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}